server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/User-db
    username: postgres
    password: 1221
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # options: validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
# Optional: logging config
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: 0123456789&abcdefghijklmnopqrstuvwxyz&9876543210
  expiration: 86400000 # 1 day in ms