server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Restaurants_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # options: validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: restaurants-service
management:
  endpoints:
      web:
        exposure:
          include: "*"
      tracing:
      sampling:
        probability: 1.0
  zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans
  endpoint:
    health:
          show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Optional: logging config
#logging:
#  level:
#    org.hibernate.SQL: NONE
#    org.hibernate.type.descriptor.sql: NONE



jwt:
  secret: 0123456789&abcdefghijklmnopqrstuvwxyz&9876543210