server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Order_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # options: validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: Order-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full


# Optional: logging config
logging:
  level:
    root: info                          # Global log level
    com.improveId.Order.service: debug         # Enable DEBUG logs for OrderService
  file:
    name: logs/order-service.log
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
    tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoint:
    health:
      show-details: always
jwt:
  secret: 0123456789&abcdefghijklmnopqrstuvwxyz&9876543210

resilience4j:
  circuitbreaker:
    instances:
      feignCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
