server:
  port: 8080

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
    management:
      tracing:
        sampling:
          probability: 1.0  # Always trace
      endpoints:
        web:
          exposure:
            include: "*"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: restaurants-service
          uri:  lb://restaurants-service
          predicates:
            - Path=/restaurant/**

        - id: Order-service
          uri: lb://Order-service
          predicates:
            - Path=/order/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**

      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
jwt:
  secret: 0123456789&abcdefghijklmnopqrstuvwxyz&9876543210
  expiration-ms: 86400000 # 24 hours

#logging:
#  level:
#    com.improveid.gateway.filter: DEBUG
#    org.springframework.web.reactive: DEBUG
#    org.springframework.cloud.gateway: TRACE